### ISSUE TITLE
抓去用户信息时不能判断是否是企业帐号

### ISSUE THREAD

**Issue by MythHack** [chineking/cola#40]
在抓取信息的时候暂时还不能判断是否是企业帐号，如果是企业帐号的话信息就会为空了~应该是少了个if神马的

![222](https://cloud.githubusercontent.com/assets/7798759/5390703/bf4f04e0-814a-11e4-9025-50908aa0e1e5.jpg)

有时还会直接catch
get 1908349515 url: http://weibo.com/1908349515/info
Error when handle bundle: 1908349515, url: http://weibo.com/1908349515/info
ValidationError (WeiboUser:54888bf6c95f801b60bce315) (site.Invalid URL: http://w
eibo.com/376765750

http://weibo.com/linuxde: ['info'])
Traceback (most recent call last):
File "D:\cola\cola\job\executor.py", line 519, in _parse_with_process_exceptio
n
res = self._parse(parser_cls, options, bundle, url)
File "D:\cola\cola\job\executor.py", line 442, in _parse
**options).parse()
File "D:\cola\contrib\weibo\parsers.py", line 605, in parse
weibo_user.save()
File "E:\Tools\Script\Python27\lib\site-packages\mongoengine\document.py", lin
e 224, in save
self.validate(clean=clean)
File "E:\Tools\Script\Python27\lib\site-packages\mongoengine\base\document.py"
, line 323, in validate
raise ValidationError(message, errors=errors)
ValidationError: ValidationError (WeiboUser:54888bf6c95f801b60bce315) (site.Inva
lid URL: http://weibo.com/376765750

**Comment by Qingmu** [comment]
通过企业微博认证的微博，头像右下方有一个蓝底的大V标志，用firebug看到其节点class="W_icon icon_pf_approve_co"，应该能通过class的这个属性去判断吧？？

**Comment by chineking** [comment]
应该是可以的，相关功能在develop merge到master后实现。
