### ISSUE TITLE
dev版本无法登录

### ISSUE THREAD

**Issue by hitalex** [chineking/cola#41]
报错提示如下：
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/kqc/github/cola/cola/job/container.py", line 123, in run
    self.init()
  File "/home/kqc/github/cola/cola/job/container.py", line 88, in init
    self.init_tasks()
  File "/home/kqc/github/cola/cola/job/container.py", line 104, in init_tasks
    is_local=self.is_local, job_name=self.job_name)
  File "/home/kqc/github/cola/cola/job/task.py", line 81, in __init**
    self.prepare()
  File "/home/kqc/github/cola/cola/job/task.py", line 102, in prepare
    self.executor.login()
  File "/home/kqc/github/cola/cola/job/executor.py", line 151, in login
    if not self._login(shuffle=random):
  File "/home/kqc/github/cola/cola/job/executor.py", line 174, in _login
    login_result = self.job_desc.login_hook(self.opener, **kw)
  File "/home/kqc/github/cola/contrib/kweibo/__init__.py", line 40, in login_hook
    return loginer.login()
  File "/home/kqc/github/cola/contrib/kweibo/login.py", line 107, in login
    json_data = json.loads(regex.search(text).group(1))
  File "/usr/lib/python2.7/json/**init**.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Counters during running:
{}
Processing shutting down
Shutdown finished
Job id:8ZcGfAqHmzc finished, spend 0.34 seconds for running

我想我是不是彻底被封了...?

**Comment by fbukevin** [comment]
我遇到相同的問題了：

```
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/veck/.                                                                                       python-eggs is writable by group/others and vulnerable to attack when used with g                                                                                       et_resource_filename. Consider a more secure location (set with .set_extraction_p                                                                                       ath or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
/home/veck/Desktop/cola/cola/core/opener.py:74: UserWarning: gzip transfer encodi                                                                                       ng is experimental!
  self.browser.set_handle_gzip(True)
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/veck/Desktop/cola/cola/worker/loader.py", line 314, in _call
    if not self._login(opener):
  File "/home/veck/Desktop/cola/cola/worker/loader.py", line 188, in _login
    login_result = self.job.login_hook(opener, **kw)
  File "/home/veck/桌面/cola/contrib/weibo/__init__.py", line 40, in login_hook
    return loginer.login()
  File "/home/veck/桌面/cola/contrib/weibo/login.py", line 106, in login
    json_data = json.loads(regex.search(unicode(text, "ISO-8859-1")).group(1))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/veck/Desktop/cola/cola/worker/loader.py", line 314, in _call
    if not self._login(opener):
  File "/home/veck/Desktop/cola/cola/worker/loader.py", line 188, in _login
    login_result = self.job.login_hook(opener, **kw)
  File "/home/veck/桌面/cola/contrib/weibo/__init__.py", line 40, in login_hook
    return loginer.login()
  File "/home/veck/桌面/cola/contrib/weibo/login.py", line 106, in login
    json_data = json.loads(regex.search(unicode(text, "ISO-8859-1")).group(1))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Finish visiting pages count: 0
Finish visiting pages count: 0
```

帳號一樣正常可以從網頁登入
