### ISSUE TITLE
在抓取过程中突然卡住三四个小时，ctrl C不会退出。应该是mq处理出现问题了

### ISSUE THREAD

**Issue by tottilin** [chineking/cola#53]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/__init__.py", line 103, in _init_process
    self.put(objs, flush=flush)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/node.py", line 407, in put
    self._remote_or_local_batch_put(addr, self.caches[addr])
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/node.py", line 348, in _remote_or_local_batch_put
    self.mq_node.batch_put(objs)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/node.py", line 151, in batch_put
    self.put(obs, force=force, priority=priority)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/node.py", line 125, in put
    priority_store.put(objs, force=force)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/store.py", line 291, in put
    result = self.put_one(obj, force, commit=False)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/store.py", line 266, in put_one
    pos = self._seek_writable_pos(m)
  File "/mnt/hgfs/crawl/cola-code/cola/core/mq/store.py", line 228, in _seek_writable_pos
    size, = struct.unpack('I', map_handle[pos:pos+4])
TypeError: 'NoneType' object has no attribute '__getitem__'

Catch interrupt signal, start to stop

**Comment by chineking** [comment]
refer to handle of https://github.com/chineking/cola/issues/59
