### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by Daisily** [chineking/cola#55]
Win 10 使用cola里面的weibo尝试抓取微博但总是报错···
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Development\Python\cola\cola\job\container.py", line 135, in run
    self.init()
  File "D:\Development\Python\cola\cola\job\container.py", line 90, in init
    self.init_tasks()
  File "D:\Development\Python\cola\cola\job\container.py", line 107, in init_tasks
    is_local=self.is_local, job_name=self.job_name)
  File "D:\Development\Python\cola\cola\job\task.py", line 86, in __init__
    self.prepare()
  File "D:\Development\Python\cola\cola\job\task.py", line 107, in prepare
    self.executor.login()
  File "D:\Development\Python\cola\cola\job\executor.py", line 161, in login
    if not self._login(shuffle=random):
  File "D:\Development\Python\cola\cola\job\executor.py", line 184, in _login
    login_result = self.job_desc.login_hook(self.opener, **kw)
  File "D:\Development\Python\cola\app\weibo\__init__.py", line 42, in login_hook
    return loginer.login()
  File "D:\Development\Python\cola\app\weibo\login.py", line 107, in login
    json_data = json.loads(regex.search(text).group(1))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by chineking** [comment]
登录就没有成功，把instance数设成1，断点到json_data = json.loads(regex.search(text).group(1))这行，看看text内容是什么

**Comment by fbukevin** [comment]
之前好像也有碰過，是否有時候微博取不到資料?

**Comment by chineking** [comment]
除非新浪微博的登录可能有不一样的行为，否则这种情况应当不常见才是。

你们都确保登录不需要验证码了么？

**Comment by Daisily** [comment]
不需要验证码，这是我自己使用的微博很正常的号

在 2016年1月19日 下午8:51，Chine King <notifications@github.com>写道：

**Comment by chineking** [comment]
OK，那就按我说的去测试一下，看看服务器返回的是个什么东西。

**Comment by Daisily** [comment]
我刚刚看了一下，运行到断点处时
json dat
是{"retcode":0,"servertime":1454272405,"pcid":"hk-35c279bd11ad0a4861357da0934250768cef","nonce":"U7VNLH","pubkey":"EB2A38568661887FA180BDDB5CABD5F21C7BFD59C090CB2D245A87AC253062882729293E5506350508E7F9AA3BB77F4333231490F915F6D63C55FE2F08A49B353F444AD3993CACC02DB784ABBB8E42A9B1BBFFFB38BE18D78E87A0E41B9B8F73A928EE0CCEE1F6739884B9777E4FE9E88A1BBE495927AC4A799B3181D6442443","rsakv":"1330428213","is_openlock":0,"exectime":5}

2016-01-20 1:17 GMT-05:00 Chine King <notifications@github.com>:

**Comment by chineking** [comment]
问题有解决吗

**Comment by Daisily** [comment]
解决了！还是我自己账号的问题，有时需要验证码有时不需要。非常感谢！
